---
abstract: 'Common helper functions without having to import them'
author:
  - 'Lukas Atkinson <amon@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.94
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Util-Underscore
requires:
  Carp: 0
  Const::Fast: 0.011
  Data::Alias: 1.18
  Data::Dump: 1.10
  List::MoreUtils: 0.07
  List::Util: 1.35
  POSIX: 0
  Path::Class: 0
  Scalar::Util: 1.36
  Try::Tiny: 0.03
  overload: 0
  perl: v5.10.1
  strict: 0
  version: 0.77
  warnings: 0
resources:
  bugtracker: https://github.com/latk/Underscore/issues
  repository: git://github.com/latk/Underscore.git
version: v1.2.0
